### ISSUE TITLE
rustup self update -- not installed

### ISSUE THREAD

**Issue by eminence** [rust-lang-nursery/multirust-rs#276] opened 2016-04-06 12:50 UTC
I'm not quite sure what to make of this:

```
achin@bigbox ~/tmp/15 $ rustup -vV
rustup 0.1.3

achin@bigbox ~/tmp/15 $ which rustup
/storage/home/achin/.cargo/bin/rustup

achin@bigbox ~/tmp/15 $ rustup self update
error: rustup is not installed at '/storage/home/achin/.cargo'
```

**Comment by brson** [comment] 2016-04-06 18:20
Weird. The check that triggers this is looking for `~/.cargo/bin/multirust`. Does that file not exist? What are the contents of `~/.cargo/bin`?

**Comment by eminence** [comment] 2016-04-06 19:54
Ahh!

```
$ ls -l ~/.cargo/bin
total 43017
-rwxr-xr-x 6 achin achin 7292552 Apr  5 21:18 cargo
-rwxr-xr-x 6 achin achin 7292552 Apr  5 21:18 rustc
-rwxr-xr-x 6 achin achin 7292552 Apr  5 21:18 rustdoc
-rwxr-xr-x 6 achin achin 7292552 Apr  5 21:18 rust-gdb
-rwxr-xr-x 6 achin achin 7292552 Apr  5 21:18 rust-lldb
-rwxr-xr-x 6 achin achin 7292552 Apr  5 21:18 rustup
```

I removed `~/.cargo/bin/multirust` because I thought that was a reasonable way to "uninstall multirust".  Was that user error?

**Comment by brson** [comment] 2016-04-06 20:42
Haha! Yeah, right now rustup installs both. I should probably go ahead and remove `multirust` from the distribution. [Here's an issue to fix that](https://github.com/rust-lang-nursery/multirust-rs/issues/284). Closing this one.

**Closed by brson** 2016-04-06 20:42 UTC

**Comment by eminence** [comment] 2016-04-06 21:04
Thanks.

To recover from this user error, I tried to re-install:

```
achin@bigbox ~/tmp/15 $ curl https://sh.rustup.rs -sSf | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

It will add the `cargo`, `rustc`, `rustup` and other commands to
Cargo's bin directory, located at:

/storage/home/achin/.cargo/bin

This path will then be added to your `PATH` environment variable by
modifying the shell startup files located at:

/storage/home/achin/.bashrc

You can uninstall at any time with `rustup self uninstall` and
these changes will be reverted.

WARNING: This is an early beta. Expect breakage.

Continue? (Y/n) y

error: toolchain 'nightly' is not installed
rustup: command failed: /tmp/tmp.EzKsDsu1fl/rustup-setup

achin@bigbox ~/tmp/15 $ cat /tmp/tmp.EzKsDsu1fl/rustup-setup
cat: /tmp/tmp.EzKsDsu1fl/rustup-setup: No such file or directory

achin@bigbox ~/tmp/15 $ find /tmp/tmp.EzKsDsu1fl
find: ‘/tmp/tmp.EzKsDsu1fl’: No such file or directory
```

I believe it's true that the nightly toolchain isn't installed, but I'm not sure why this is an error.

**Comment by Ketsuban** [comment] 2016-05-26 13:42
For the benefit of those arriving from Google, the issue is trivially circumvented by creating the file `$HOME/.cargo/bin/multirust`—rustup doesn't actually care what the file is, it's just checking it's there.
